### ISSUE TITLE
TerrainF uudelleennimeämiset

### ISSUE THREAD

**Issue by aheiska** [tPeltola/loputon-laiskuus#10]
TerrainF on huono nimi. Ehdotus: 
a) Terrain -> RawLevel 
b) TerrainF -> Terrain

Näistä b on selviö. Terrain:n korvike vaikeampi nimetä

**Comment by tPeltola** [comment]
a) LevelVector? Se oli alkuperäinen muuttujanimi. Level olisi muuten hyvä, mutta se on jo käytössä.

**Comment by aheiska** [comment]
Ehkä tuo LevelVector on parempi. Level olisi tosiaan ehkä paras, mutta sitten en kyllä keksi mitään järkeää tuolle nykyiselle Level:lle muuta kuin jonkun keinotekoisen LevelData:n tjsp

**Comment by aheiska** [comment]
Hmm, LevelVector => Plane?

**Comment by tPeltola** [comment]
Planesta tulee ekana mieleen taso matemaattisena terminä, mutta se taitaa olla vain omaa ennakkoluuloisuuttani.

**Comment by aheiska** [comment]
Otetaan LevelVector. Se kertoo suoraan mistä on kyse.
