### ISSUE TITLE
Teoriakalvot Haskellin syntaksista

### ISSUE THREAD

**Issue by tPeltola** [tPeltola/loputon-laiskuus#5]
- pattern matching (guard)
- tietotyypit
  - "enum"
  - constructorit
  - deriving(?)
- $ <-> ()
- tyyppisignaturet
- currying(?)
- /= vs !=

**Comment by aheiska** [comment]
* Vector vs. []
* Record syntaksi ja jäsenen accessointi
** Uuden instanssin luonti vanhan pohjalta
* Tarviiko `.` selittää
* Tarvitut tietotyypit on määritelty, deriving voinee mennä vähemmällä huomiolla
* Maininta negatiivisesta luvusta (taitaa olla vain annetussa koodissa)

**Comment by aheiska** [comment]
Pari annettua funktiota on point free, pitäisikö tästä pyrkiä eroon?

**Comment by tPeltola** [comment]
Ehkä, harkitsin samaa itsekin. Minulla ainakin meni aika kauan ennen kuin tajusin, miten ne toimivat ja koska ei ole oleellista tehtävän kannalta, niin en jäisi kyllä kaipaamaan.
