### ISSUE TITLE
Pohjaratkaisun yksinkertaistus

### ISSUE THREAD

**Issue by tPeltola** [tPeltola/loputon-laiskuus#8]
- Poista . ?
- findChar ja Maybe?
- isLegal parametrit toisinpäin (merkitystä vain jos haluaa kirjoittaa point-free haskellia)
- laveammat importit (erityisesti Set: member, insert. Prefixilla?)

**Comment by aheiska** [comment]
findChar voisi varmasti olla eleganti ja enemmän haskellmainen. Jos menee kovin kiharaiseksi niin voinee tarjota valmiina.

**Comment by tPeltola** [comment]
findChar olisi helpompi tehdä, jos paluuarvo olisi Maybe Pos ja käyttäisi do-notaatiota. Se taas vaatii hyötyynsä nähden aika paljon teoriaa. Toinen mahdollisuus on, että kirjoittaa siihen avuksi findIndex ja elemIndex ilman Maybea...

**Comment by tPeltola** [comment]
Poistin point-freet ja tein findCharin yhteyteen findIndex' ja elemIndex', jotka purkavat Mayben.
